version: "3.5"

services:
    git-rate-auth:
        container_name: git-rate-auth
        depends_on:
            - 'postgres-db'
        build:
            context: ./src/backend
            dockerfile: DockerfileAuth
        ports:
            - '5000:5000'
        environment:
            ASPNETCORE_ENVIRONMENT: 'Development'
            
    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        ports:
            - '5432:5432'
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
    
volumes:
    postgres-db-volume: